version: '3.8'

services:
  db: 
    container_name: "kotts_database"
    image: mysql:8
    ports:
    - "3306:3306"
    environment:
      MYSQL_DRIVER: "mysql"
      MYSQL_HOST: "kott.czve4izeamxt.us-east-2.rds.amazonaws.com"
      MYSQL_DATABASE: "kottdb"
      MYSQL_ROOT_PASSWORD: "Metroboomin50"
    restart: always
    volumes:
      - /vol/kbd:/var/lib/mysql
    networks:
      - kotts_default

  api:
    container_name: "kotts_backend"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - /vol/kbe:/app/
    ports:
      - "8080:8080"
    networks:
      - kotts_default


networks:
  kotts_default:

volumes:
  kbd:
  kbe: