version: '3.8'

services:
  api:
    container_name: "kotts_backend"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    ports:
      - "8080:8080"
networks:
  default: